easy_admin:
  entities:
    Article:
      class: App\Entity\Article
      show:
        fields:
          - {property: 'title' }
          - {property: 'image', type: 'image', base_path: '%app.path.article_images%' }
          - {property: 'tags' }
          - {property: 'description' }
          - {property: 'published' }
          - {property: 'slug' }
          - {property: 'favorite' }
          - {property: 'categorie' }
          - {property: 'imgAlternate' }
      list:
        fields:
          - 'title'
          - 'slug'
          - {property: 'image', type: 'image', base_path: '%app.path.article_images%' }
          - 'published'
          - 'favorite'
      form:
        fields:
          - {property: 'title' , type_options: { required: true } }
          - {property: 'description' }
          - {property: 'imageFile', type: 'vich_image', type_options: {}  }
          - {property: 'imgAlternate' }
          - {property: 'text',type: 'FOS\CKEditorBundle\Form\Type\CKEditorType', type_options: { config_name: 'advanced_config',required : true } }
          - {property: 'tags' }
          - {property: 'categorie' }
          - {property: 'slug', type_options: { required: false }  }
          - {property: 'allowComment',  type: 'choice', type_options: { multiple: true, choices: { 'Afficher les commentaires': 'allowComment', 'Valider les commentaires automatiquement': 'commentValidatingAuto', 'Pas commentaire': 'noComment' } } }
          - {property: 'published' }
          - {property: 'favorite' }
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
